import 'bootstrap/dist/css/bootstrap'
import 'react-s-alert/dist/s-alert-default'
import 'react-s-alert/dist/s-alert-css-effects/scale'
import 'react-datepicker/dist/react-datepicker'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme'
