env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  no-unused-vars: ["error", { "varsIgnorePattern": "[rR]eact", "args": "none" }]
  react/display-name: 0